### ISSUE TITLE
Question No 12 and Question No 13 / 15.1 - Question No 13 should not be displayed on selecting “No” in Question No 12 of the Diabetes check.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#100]
1. Goto Question No 12
2. Under “Diabetes is one of the most debilitating chronic disease.” Select “No”.

Question No 13 asking for “What were your fasting blood sugar levels then?” is displayed

Question No 13 should not be displayed

Need to discuss on this

**Comment by shanthasprim** [comment]
Fixed.
