### ISSUE TITLE
Question No 12 / 16.1 - Answering Question 12 as 'Yes' or 'No' shows the same page.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#101]
## Steps To Reproduce
1. Goto Question No 12
2. Under “Diabetes is one of the most debilitating chronic disease.” Select “Yes”.
## Actual Result

Question No 13 asking for “What were your fasting blood sugar levels then?” is displayed
## Expected Result

Question should be changed
## Comments

Need to discuss on this

**Comment by shanthasprim** [comment]
Not an issue
