### ISSUE TITLE
Question No 13 / 17.1 - Hand symbol is shown on 'Mouse Over' on the text “What were your fasting blood sugar levels then?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#102]
## Steps To Reproduce

Do a  'Mouse Over' on the text “What were your fasting blood sugar levels then?” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display fixed
