### ISSUE TITLE
Question No 13 / 17.2 - Clicking on the “Blood sugar Levels” images sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#103]
## Steps To Reproduce
1. Goto Question No 13
2. Click on any “Blood sugar Levels” image
## Actual Result

Clicking on the “Blood Pressure image sometimes shows the image icon border 
## Expected Result

Clicking on the “Blood Pressure” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Display fixed
