### ISSUE TITLE
Question No 13 / 17.3 - Clicking on the “Blood sugar Levels” image showing the image icon border is not saved 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#104]
## Steps To Reproduce
1. Goto Question No 13
2. Click on any “Blood sugar Levels” image (image border is shown)
3. Click on “Next” button.
4. Click on “Back” button in Question No 14 page.
## Actual Result

The selected “Blood sugar Levels” image value is not shown on the Ques No 13 page
## Expected Result

The selected “Blood sugar Levels” image value should be stored and shown on the Ques No 13 page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Display fixed. Hence not reproducible.
