### ISSUE TITLE
Question No 14 / 18.1 - Hand symbol is shown on 'Mouse Over' on the text “It is nice to visit your family doctor regularly to get a whole body checkup done regularly. When was the last time you visited your doctor?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#105]
## Steps To Reproduce

Do a  'Mouse Over' on the text “It is nice to visit your family doctor regularly to get a whole body checkup done regularly. When was the last time you visited your doctor?” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display fixed.
