### ISSUE TITLE
Question No 14 / 18.2 - Clicking on the “Planning Regular Checkup” images sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#106]
## Steps To Reproduce
1. Goto Question No 14
2. Click on any “Planning Regular Checkup” image
## Actual Result

Clicking on the “Planning Regular Checkup” image sometimes shows the image icon border 
## Expected Result

Clicking on the “Planning Regular Checkup” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Display fixed.
