### ISSUE TITLE
Question No 14 / 18.3 - Clicking on the “Planning Regular Checkup” image showing the image icon border is not saved 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#107]
## Steps To Reproduce
1. Goto Question No 14
2. Click on any “Planning Regular Checkup” image (image border is shown)
3. Click on “Next” button.
4. Click on “Back” button in Question No 15 page.
## Actual Result

The selected “Planning Regular Checkup” image value is not shown on the Ques No 14 page
## Expected Result

The selected “Planning Regular Checkup” image value should be stored and shown on the Ques No 14 page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Display fixed. Hence issue not reproducible.
