### ISSUE TITLE
HRA_Man_Question No 15 / 19.1 - Hand symbol is shown on 'Mouse Over' on the text “I check for swelling in my groin area during a shower once a month”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#108]
## Steps To Reproduce

Do a  'Mouse Over' on the text “I check for swelling in my groin area during a shower once a month” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

Precondition:
The Gender to be selected as 'Man'

**Comment by shanthasprim** [comment]
Display Fixed.
