### ISSUE TITLE
Question No 16 / 20.1 - Question No 16 does not allow the user to go to Ques No 17 without selecting any “Lifestyle Choices” value but does not display any error message

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#111]
## Steps To Reproduce
1. Goto Ques No 16.
2. Dont select any check box and click on “Next” button
## Actual Result

Question No 16 does not allow the user to go to Ques No 17 without selecting any “Lifestyle Choices” value
## Expected Result

Question No 16 should not allow the user to go to Ques No 17 without selecting any “Lifestyle Choices” value and show a error message saying “Please select any option to proceed”

**Comment by shanthasprim** [comment]
"Please select any option" error message is displayed.
