### ISSUE TITLE
Question No 16 / 20.2 - The other check box options should be greyed out (Made Readonly) when the user selects “None of the above” option

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#112]
## Steps To Reproduce
1. Goto Ques No 16.
2. check the “None of the above” option.
## Actual Result

The other check box options are visible
## Expected Result

The other check box options should be greyed out.
On the Second click of the same “None of the above” Option, It should be unchecked and the other options should be visible.
## Comments

When a user selects  “None of the above” we need not show him the other option.
Selecting “None of the above” and adding other checkbox values will not be a correct functionality.

**Comment by shanthasprim** [comment]
Not an issue
