### ISSUE TITLE
Question No 16 / 20.3 - Hand symbol is shown on 'Mouse Over' on the text “Your lifestyle describes a lot about your health and is an important parameter to assess your health.”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#113]
## Steps To Reproduce

Do a  'Mouse Over' on the text “Your lifestyle describes a lot about your health and is an important parameter to assess your health.” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed
