### ISSUE TITLE
Question No 17 / 21.1 - The Thermometer image which shows “Never”, “Somewhat” and “Very” loads or changes very slowly on change of the check box selection

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#114]
## Steps To Reproduce
1. Goto Ques No 17.
2. check one or more options.
3. Change the selction to check the thermometer image loading.
## Actual Result

The image change is not correlating with the  selection change
## Expected Result

The image should load correctly on change of the Selection options
## Comments

The image change is happening but very slowly and does not do properly when the selction option is more than one and changed for more than once

**Comment by shanthasprim** [comment]
User has to select the level in the thermometer
