### ISSUE TITLE
Question No 17 / 21.2 - Question No 17 does not allow the user to go to Ques No 18 without selecting any “Triggers for stress” value but does not display any error message

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#115]
## Steps To Reproduce
1. Goto Ques No 17.
2. Dont select any check box and click on “Next” button
## Actual Result

Question No 17 does not allow the user to go to Ques No 18 without selecting any “triggers for stress” value
## Expected Result

Question No 17 should not allow the user to go to Ques No 18 without selecting any “triggers for stress” value and show a error message saying “Please select any option to proceed”

**Comment by shanthasprim** [comment]
"Please select any option" error message is displayed.
