### ISSUE TITLE
Question No 17 / 21.3 - Hand symbol is shown on 'Mouse Over' on the text “How stressed do you get?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#116]
## Steps To Reproduce

Do a  'Mouse Over' on the text “How stressed do you get?” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display fixed
