### ISSUE TITLE
Question No 17 / 21.4 - The Phrase “How stressed do you get?” should be rephrased as “How stressed are you?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#117]
## Steps To Reproduce

Goto Question No 17 and check the title
## Actual Result

Title displayed as “How stressed do you get?”
## Expected Result

The Phrase “How stressed do you get?” should be rephrased as “How stressed are you?”

**Comment by shanthasprim** [comment]
Fixed.
