### ISSUE TITLE
Question No 18 / 22.1 -  Hand symbol is shown on 'Mouse Over' on the text “How many hours do you sleep daily on an average?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#118]
## Steps To Reproduce

Do a  'Mouse Over' on the text “How many hours do you sleep daily on an average?” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed
