### ISSUE TITLE
Question No 18 / 22.2 - The “5-7 hours” shows a clock image in yellow which looks more or less like green

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#119]
## Steps To Reproduce
1. Goto Question No 18
2. Click on “5-7 hours” option button.
3. Check the Clock image displayed on the right hand side.
## Actual Result

A Clock image is displayed in Greenish yellow colour
## Expected Result

A Clock image display can be made as a bright yellow colour as it looks more or less like green

**Comment by shanthasprim** [comment]
Difference is visible now.
