### ISSUE TITLE
Question No 19 / 23.1 - Hand symbol is shown on 'Mouse Over' on the text “I consume products containing tobacco such as cigarettes, smokeless tobacco, cigars and pipes?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#120]
## Steps To Reproduce

Do a  'Mouse Over' on the text “I consume products containing tobacco such as cigarettes, smokeless tobacco, cigars and pipes?” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed
