### ISSUE TITLE
Question No 19 / 23.2 - Clicking on the “consume products containing tobacco” images sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#121]
## Steps To Reproduce
1. Goto Question No 19
2. Click on any “consume products containing tobacco” image
## Actual Result

Clicking on the “consume products containing tobacco” image sometimes shows the image icon border 
## Expected Result

Clicking on the “consume products containing tobacco” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Display Fixed.
