### ISSUE TITLE
Question No 19 / 23.3 - Clicking on the “consume products containing tobacco” image showing the image icon border is not saved 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#122]
## Steps To Reproduce
1. Goto Question No 19
2. Click on any “consume products containing tobacco” image (image border is shown)
3. Click on “Next” button.
4. Click on “Back” button in Question No 20 page.
## Actual Result

The selected “consume products containing tobacco” image value is not shown on the Ques No 19 page
## Expected Result

The selected “consume products containing tobacco” image value should be stored and shown on the Ques No 19 page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Display Fixed. Hence could not reproduce this issue.
