### ISSUE TITLE
Question No 21 / 25.1 - Hand symbol is shown on 'Mouse Over' on the text “I restrict food rich in fats such as fried foods, butter, cheese etc.”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#124]
## Steps To Reproduce

Do a  'Mouse Over' on the text “I restrict food rich in fats such as fried foods, butter, cheese etc.” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed
