### ISSUE TITLE
Question No 22 / 26.1 - Hand symbol is shown on 'Mouse Over' on the text “While shopping, I read food labels before purchasing a product.”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#125]
## Steps To Reproduce

Do a  'Mouse Over' on the text “While shopping, I read food labels before purchasing a product.” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display fixed
