### ISSUE TITLE
HRA_Woman_Question No 23 / 28.1 - Hand symbol is shown on 'Mouse Over' on the text,“I examine my breasts at least once a month”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#129]
## Steps To Reproduce

Do a  'Mouse Over' on the text “I examine my breasts at least once a month” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

Precondition:
The user should select the Gender as “Woman”

**Comment by shanthasprim** [comment]
Display Fixed
