### ISSUE TITLE
Adding a Patient through Invite by the HCP should not allow the HCP to enter the non existing or invalid Email Id 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#13]
## Steps to reproduce
1. Login into DGC with HCP Login
2. Click HCP dropdown on the top left of the header
3. Click 'My Patients' -> '+Add Patient'
4. Enter the 'Email or User name' field value which is not there in the drop down.
## Actual Result

The value is added but is not added under the list.Does not display any error message
## Expected Result

Error message should be displayed as “Please enter Existing DGC Email or User name. If you want to add a new user, Please click 'New User' button below”

**Comment by shanthasprim** [comment]
Working as Expected. Need to highlight error message in red color.
