### ISSUE TITLE
HRA_Woman_Question No 23 / 28.2 - Clicking on the “Examine my breasts” images sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#130]
## Steps To Reproduce
1. Goto Question No 23
2. Click on any “Examine my breasts” image
## Actual Result

Clicking on the “Examine my breasts” image sometimes shows the image icon border 
## Expected Result

Clicking on the “Examine my breasts” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Display Fixed
