### ISSUE TITLE
HRA_Woman_Question No 23 / 28.3 - Clicking on the “Examine my breasts” image showing the image icon border is not saved 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#131]
## Steps To Reproduce
1. Goto Question No 23
2. Click on any “Examine my breasts” image (image border is shown)
3. Click on “Next” button.
4. Click on “Back” button in Question No 24 page.
## Actual Result

The selected “Examine my breasts” image value is not shown on the Ques No 23 page
## Expected Result

The selected “Examine my breasts” image value should be stored and shown on the Ques No 23 page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Display Fixed. Hence could not reproduce this issue
