### ISSUE TITLE
HRA_Woman_Question No 24/ 29.2 - Clicking on the “Now tell us, how your menses are.” images sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#133]
## Steps To Reproduce
1. Goto Question No 24
2. Click on any “Now tell us, how your menses are.” image
## Actual Result

Clicking on the “Now tell us, how your menses are.” image sometimes shows the image icon border 
## Expected Result

Clicking on the “Now tell us, how your menses are.” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Display Fixed
