### ISSUE TITLE
HRA_Woman_Question No 24/ 29.3 - “Now tell us, how your menses are.”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#134]
## Steps To Reproduce
1. Goto Question No 24
2. Click on any “Examine my breasts” image (image border is shown)
## Actual Result

The selected “Examine my breasts” image value is not shown on the HRA results report page
## Expected Result

The selected “Examine my breasts” image value should be stored and shown on the HRA results report page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Display Fixed. Hence could not reproduce this issue.
