### ISSUE TITLE
Congratulations Page - 30.1 - The Phrase “Yoy have completed the Health Risk Assesment! ” should be rephrased as “You have completed the Health Risk Assesment! ” 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#135]
## Steps To Reproduce
1. Complete all the Questions
## Actual Result

The Congratulations page is displayed with the text “Yoy have completed the Health Risk Assesment! “
## Expected Result

The Congratulations page should be displayed as “You have completed the Health Risk Assesment! “
## Comments

Spelling Error

**Comment by shanthasprim** [comment]
Fixed.
