### ISSUE TITLE
Health Risk Report Page / 33.1 - The '†' displayed in many places of the Health Risk Report Page

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#136]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Check 'Physical” -> BMI section, before the word “†overweight”
3. Check Lipid Panel -> Total Cholestrol, before the word “†However”
4. Check Lipid Panel -> HDL, before the word “†A high”
5. Check Lipid Panel -> Tryglyceride, before the word “†alcohol”
6. Check Lifestyle 
7. Check the Diet 
8. Check How many times eat out
## Actual Result

The '†' displayed in many places of the Health Risk Report Page
## Expected Result

The '†' should not be displayed in  the Health Risk Report Page

**Comment by shanthasprim** [comment]
Issue fixed.
