### ISSUE TITLE
Health Risk Report Page / 33.2 - A column is displayed below the BMI column without any header

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#137]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Check Physical -> BMI
## Actual Result

A column is displayed below BMI
## Expected Result

A column is displayed below the BMI column without any header
## Comments

Make a note above the column to identify where the value comes from

**Comment by shanthasprim** [comment]
Fixed
