### ISSUE TITLE
Health Risk Report Page / 33.3 - Spacing between the Family history values

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#138]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Check Medical -> Family History
## Actual Result

The Selected values for Family History is shown without space
## Expected Result

The Selected values for Family History should be displayed with space
## Comments

To Check this more than one value for Family history to be selected.

**Comment by shanthasprim** [comment]
Displayed with proper spacing now.
