### ISSUE TITLE
Health Risk Report Page / 33.4 - The Planning regular checkup value is shown without a header

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#139]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Check Lifestyle under the hourglass segment
## Actual Result

The selected value is just displayed without a header
## Expected Result

The selected value should be displayed with a header as 'Pkanning regular checkups'

**Comment by shanthasprim** [comment]
Lifestyle Header is displayed with the subtitle as 'Last Doctor Visit'
