### ISSUE TITLE
The HCP should not be able to select Time slots for the present day when the timeslot is already over  Check the time when the HCP opens the page (say if he logs in at 11:00 am, the time slots before that should be disabled) check the time and disable the finished time slots.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#14]
## Steps to reproduce
1. Login into DGC with HCP Login
2. Click HCP dropdown on the top left of the header
3. Click 'Appointment Availability'
4. Check for the present day's time slots.
## Actual Result

The time slots from 7:00 Am till 9:00 PM is displayed
## Expected Result

The HCP should not be able to select Time slots for the present day when the timeslot is already over 
Check the time when the HCP opens the page (say if he logs in at 11:00 am, the time slots before that should be disabled) check the time and disable the finished time slots.

**Comment by shanthasprim** [comment]
Working as Expected. Hence Closing the issue.
