### ISSUE TITLE
Health Risk Report Page - The Physical activity times message has invalid value and some images does not load

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#140]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Check  Lifestyle under the physical activity times segment
## Actual Result

The Physical activity times message is  displayed.
## Expected Result

The Physical activity times message is not displayed correctly.
“Adults require at least ñ”

**Comment by shanthasprim** [comment]
![hra_report_1](https://cloud.githubusercontent.com/assets/7219964/6184569/845e3902-b389-11e4-8325-22a4d0691cb7.png)
![hra_report_2](https://cloud.githubusercontent.com/assets/7219964/6184570/846ad36a-b389-11e4-8052-4c6773586f78.png)

**Comment by vijayhegde1** [comment]
Its already fixed it seems.

**Comment by shanthasprim** [comment]
Working as Expected.
