### ISSUE TITLE
Health Risk Report Page / 33.6 - The Misc section is not displayed when the Gender is selected as 'Woman”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#141]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Check Misc section
## Actual Result

No data is displayed
## Expected Result

The selected Misc data should be displayed
## Comments

This happens only when the user selects the Gender as 'Woman”

**Comment by shanthasprim** [comment]
Fixed and Misc section is displayed now.
