### ISSUE TITLE
Status Progress bar / 35.1 - Provide a Completion progress % or Question no 2 Out of 23 to make user know about the completion target

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#142]
## Steps To Reproduce
1. Sign in as any user
2. Click on the user name drop down and select 'Profile'
3. Click on “Improve Your Score' under “Health Risk”
4. Click on  “Test again” button
5. Check the Status bar below the Questions provided as you go on clicking the next question.
## Actual Result

A Green status bar is displayed
## Expected Result

A Green status bar should be displayed with a Completion progress % or Question no 2 Out of 23 to make user know about the completion target
## Comments

This will make the user clear or give information to the user about the completion status

**Comment by shanthasprim** [comment]
Duplicate issue hence closing it
