### ISSUE TITLE
Hand Symbol on Clickcables / 36.1 - Provide Hand symbol on all the clickables under HRA

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#143]
## Steps To Reproduce

Check all the pages in HRA
## Actual Result

Hand symbol is displayed for few clickables and not shown in many
## Expected Result

Provide Hand symbol on all the clickables under HRA
Clickables include:
1. Checkbox,
2. Option button
3. buttons

**Comment by shanthasprim** [comment]
Fixed. Hand symbol is shown where it is clickable
