### ISSUE TITLE
Cursor on input box / 37.1 - Provide cursor symbol on all the input boxes where user is expected to enter any data under HRA

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#144]
## Steps To Reproduce

Check all the pages in HRA
## Actual Result

Cursor symbol is displayed for few inputbox and not shown in many
## Expected Result

Provide cursor symbol on all the input boxes where user is expected to enter any data under HRA

**Comment by shanthasprim** [comment]
Fixed. Cursor symbol is displayed for the text box
