### ISSUE TITLE
Click link / 38.1 - Allow the user to click on the text incase of option or check box instead of allowing him to click only on the option or the check box.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#145]
## Steps To Reproduce

Check all the pages in HRA
## Actual Result

Allows the user to click on the text in some places of option or check box
## Expected Result

In case of Option or Check box, allow the user to click on the text also to select a particular option instead of allowing him to click only on the option or the check box.

**Comment by shanthasprim** [comment]
Working as Expected. Clicking on the text also selects the Check box / Option button.
