### ISSUE TITLE
Email Report (Congratulations Page)  / 31.1 - “Email Report” button is not active in the “congratulations” page

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#147]
## Steps To Reproduce
1. Complete all the Questions
2. In the displayed Congratulations page, Click on  “Email Report” button
## Actual Result

“Email Report” button is not active in the “congratulations” page
## Expected Result

“Email Report” button should be active in the “congratulations” page

**Comment by shanthasprim** [comment]
Clicking the 'Email Report' button sends mail but the button is shown as read-only. Not an issue
