### ISSUE TITLE
Email Report (Health Risk Report Page) / 32.1 - Show “Sending mail.Please Wait.” loading message and image when user clicks on “Email Report” button.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#148]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Click on  “Email Report” button
## Actual Result

Does not show anything to the user but shows “Successfully E-mailed your report.” after sometime.
## Expected Result

Show “Sending mail.Please Wait.” loading message and image when user clicks on “Email Report” button.
## Comments

User may not know if the mail is being sent or not. Showing a loading message intimates them that Process is inprogress.

**Comment by shanthasprim** [comment]
Mail is sent immediately. so no need for this messaging.
