### ISSUE TITLE
Email Report (Health Risk Report Page) / 32.2 - Clicking “Email Report” button does not send email to the provided mail id for a HCP user

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#149]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Click on  “Email Report” button
## Actual Result

shows “Successfully E-mailed your report.”
## Expected Result

shows “Successfully E-mailed your report.”. But email is not sent actually
## comments

The Login should be created as a HCP user

**Comment by shanthasprim** [comment]
Working as Expected now.
