### ISSUE TITLE
Formatting for the calendar needed 1. The 'March Events' text goes under the date grid, When the date grid has 6 rows. 2. The days value 'mon','tue','wed' etc need to be as 'Mon','Tue','Wed' etc

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#15]
## Steps to reproduce
1. Login into DGC with HCP Login
2. Click HCP dropdown on the top left of the header
3. Click 'My Appointments'
4. Click on 'Calendar' button on the right top 
## Actual Result
1. The 'March Events' text goes under the date grid, When the date grid has 6 rows.
2. The days value 'mon','tue','wed' etc need to be as 'Mon','Tue','Wed' etc
## Expected Result

Formatting should be done

**Comment by shanthasprim** [comment]
Fixed and Working as Expected.
