### ISSUE TITLE
Email Report (Health Risk Report Page) / 32.3 - Clicking “Email Report” button does not send email to the provided mail id for a user

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#150]
## Steps To Reproduce
1. Goto Health Risk Report Page.
2. Click on  “Email Report” button
## Actual Result

shows “Successfully E-mailed your report.”
## Expected Result

shows “Successfully E-mailed your report.”. But email is not sent actually

The Login should be created as Iam a user

**Comment by shanthasprim** [comment]
This issue is fixed now
