### ISSUE TITLE
Email Report (Health Risk Report Page) / 32.4 - Clicking “Email Report” button does not send email without taking HRA (Should be for all user Sign in types)

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#151]
## Steps To Reproduce
1. Sign in as any user
2. Click on the user name drop down and select 'Profile'
3. Click on “Improve Your Score' under “Health Risk”
4. Click on  “Email Report” button
## Actual Result
1. shows “Successfully E-mailed your report.” in then page.
2. Mail is actually sent but the mail does not have any report in it.
## Expected Result

Mail should be sent with the report in it.
## Comments

The mail is sent only when the user takes up the HRA Test and click on the “Email Report” button.
Logging in and directly clicking on the  “Email Report” button doesnot send the report properly.

**Comment by shanthasprim** [comment]
HRA report is received now anytime.
