### ISSUE TITLE
The HCP Profile page is not displayed with complete Profile details with the 'more' link

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/DGC-Web#159]
## Steps To Reproduce:
1. Login as any user
2. Check the Health Coach and open the "View Profile" for any HCP under the 'My' Filter section
## Actual Result:

The content of the profile section is displayed lesser
## Expected Result:

The entire Profile content should be displayed with a 'more' link to view the complete details.
## Precondition:

Health Coach to be added already for the logged in user.

**Comment by sprimit** [comment]
@shanthasprim  on mac Firefox and Chrome working fine. Which browser give this problem. Add details.

**Comment by vijayhegde1** [comment]
HCP specialities and profiles are at the top and other details like Education, Hospital Affilation, Awards..etc are at the bottom (after "Book an Appointment with DGC Experts" block)

**Comment by shanthasprim** [comment]
I have checked in Windows IE and Mozilla. both are having this issue,
When logged in as user (sprim demo) and view the 'HCP Profile' (Sprim Demo2). There are some more details to show. But there is no 'More' button to expand and see the details.
![issue159_1](https://cloud.githubusercontent.com/assets/7219964/6665446/ae507a02-cbff-11e4-9daf-7905390a0c50.png)
Only displays till 'He also penned several bestselling self-help books.' text. but some more text is available after it 'Early Life  Psychologist,.... '
![issue159_2](https://cloud.githubusercontent.com/assets/7219964/6665471/e69ad650-cbff-11e4-891b-f1d3fbc99ddd.png)

**Comment by vijayhegde1** [comment]
Its working in Mozilla and Chrome. unable to reproduce.

**Comment by shanthasprim** [comment]
Was reproducible sometimes. But now could not reproduce the scenario.
