### ISSUE TITLE
Year should be displayed along with the date field for the tabs 'Future Appointments' and 'Appoinments Pending Approval'

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#19]
## Steps to reproduce
1. Login into DGC with HCP Login
2. Click HCP dropdown on the top left of the header
3. Click 'My Appointments'
4. Click on 'Future Appointments' tab and check the date column
5. Click on 'Appoinments Pending Approval' tab and check the date column
## Actual Result

Day and month are displayed
## Expected Result

Day and month should be displayed along with the year

**Comment by mghipparagi** [comment]
![hcp_myappointment_datesorting](https://cloud.githubusercontent.com/assets/1898079/2654850/218e8d00-bfdc-11e3-9e1d-9ac2a8e13446.png)

**Comment by shanthasprim** [comment]
The Date column includes the year. But the Search Filter still does not include the year.
![issue19](https://cloud.githubusercontent.com/assets/7219964/6685293/80e75f62-ccbe-11e4-95f7-509284b7086d.png)

**Comment by shanthasprim** [comment]
Working as Expected. Hence closing the issue.
