### ISSUE TITLE
The Patients drop down list should not show the Logged in HCP's name

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#20]
## Steps to reproduce
1. Login into DGC with HCP Login
2. Click HCP dropdown on the top left of the header
3. Click 'My Appointments'
4. Click on 'Add Appointments”
5. Click on 'Patient' drop down
## Actual Result

The Logged in HCP name is displayed
## Expected Result

The Logged in HCP name should not be displayed

**Comment by shanthasprim** [comment]
Working as Expected. Hence Closing this issue
