### ISSUE TITLE
The Page Entry displayed at the bottom of the HCP List grid should be aligned properly

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#27]
## Steps to reproduce
1. Login to DGC with admin Login
2. Click on HCP Header and select 'HCP List' from the drop down.
   3.scroll down the page
## Actual Result

The page number for the HCP list is displayed without alignment
## Expected Result

The page number for the HCP list should be displayed with proper alignment
![addhcp_hcplist_pagealignment](https://cloud.githubusercontent.com/assets/1898079/2655005/18c05980-bfdf-11e3-8aba-fcb71a0f7e92.png)

**Comment by shanthasprim** [comment]
Fixed and Working as Expected.
