### ISSUE TITLE
The 'Postal Code' value should not accept special characters other than hiphen '-' in the HCP Edit page

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#28]
## Steps to reproduce
1. Login to DGC with admin Login
2. Click on HCP Header and select 'HCP List' from the drop down.
   3.Click on Edit button for any HCP detail
3. Change the postal code to  '$#@%$^%'
4. Click on the 'Save' button
## Actual Result

The HCP entry is saved
## Expected Result

HCP Entry should not be saved

**Comment by shanthasprim** [comment]
Postal codeacceptsonly positive numbers. If entered invalid entry shows an error message as "The Postal Code field must contain only positive numbers.".
