### ISSUE TITLE
Cancel Button in the HCP Edit page

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#30]
## Steps to reproduce
1. Login to DGC with admin Login
2. Click on HCP Header and select 'HCP List' from the drop down.
   3.Click on Edit button for any HCP detail
## Actual Result

There is no Cancel button if the admin does not want to edit
## Expected Result

Cancel button should be provided

**Comment by shanthasprim** [comment]
Getting a db error page on clicking Cancel button in the HCP Profile Edit page.
![issue30](https://cloud.githubusercontent.com/assets/7219964/6684778/686ec1ea-ccba-11e4-993a-183353d39dfd.png)

**Comment by vijayhegde1** [comment]
Cancel Button added

**Comment by shanthasprim** [comment]
Error page is not displayed now. Hence closing the issue.
