### ISSUE TITLE
Remove the buttons for the fields 'Awards', 'Publications' and 'Bio-data' other than the Font formatting options in the HCP Edit page.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#31]
## Steps to reproduce
1. Login to DGC with admin / any Login
2. Click on HCP Header and select 'HCP List' from the drop down.
   3.Click on Edit button for any HCP detail
3. Check 'Awards', 'Publications' and 'Bio-data' fields
## Actual Result

More options are available for these fields
## Expected Result

Remove all the options except the Font formatting options

**Comment by shanthasprim** [comment]
Done and Working as Expected.
