### ISSUE TITLE
Question No 1 - Question No 1 allows “Select Age” value to be added in the “Age” field

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#36]
## Steps To Reproduce
1. Goto Question No 1
2. Click on “Age” field
3. Select the value “Select Age” from the drop down
4. Enter other values
5. Swipe to the next Question
## Actual Result

It allows the user to proceed with the next question
## Expected Result

It should not allow user to goto the next question
## Comments

Make the “Select Age” option readonly.

**Comment by shanthasprim** [comment]
"Select age" made as readonly now
