### ISSUE TITLE
Question No 1- Restrict the Weight value length to 3 digits (in Kgs) and  3 digits (in lbs) 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#38]
## Steps To Reproduce
1. Enter the “Age” value.
   2.Enter the weight value as '453465'
## Actual Result

Weight value is accepted
## Expected Result

Weight value length has to be restricted
## Comments

In realtime scenario Human Weight cannot be higher value

**Comment by shanthasprim** [comment]
validation done
