### ISSUE TITLE
Question No 1/ 1.3 - Restrict the Height value only with number and not any alphabets / special characters.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#40]
## Steps To Reproduce
1. Enter the “Age” value.
   2.Enter the weight value as '1534545.4534545'
## Actual Result

Weight value is accepted
## Expected Result

Weight value should not be accepted
## Comments

Invalid Weight value

**Comment by shanthasprim** [comment]
Validation done
