### ISSUE TITLE
Question No 1/ 1.4 - Restrict the Height value length to 2 digits (in “ft &in”) and 3 digits (in cms)

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#43]
## Steps To Reproduce
1. Enter the “Age” value
2. Enter the “Height value as “11111111111”
## Actual Result

Height value is accepted
## Expected Result

Height value length has to be restricted
## Comments

In realtime scenario Human height cannot be higher value

**Comment by shanthasprim** [comment]
validation done
