### ISSUE TITLE
Question No 1 / 1.4 - Restrict the Height value with one number before and after the decimal point

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#44]
## Steps To Reproduce
1. Enter the “Age” value.
   2.Enter the Height value as '1534545.4534545'
## Actual Result

Height value is accepted
## Expected Result

Height value length has to be restricted
## Comments

Invalid height value

**Comment by shanthasprim** [comment]
Decimal points are not accepted

**Comment by vijayhegde1** [comment]
validations done
