### ISSUE TITLE
Question No 1/ 1.5 - BMI Calculation can be shown on load / on entry of the 'Height' 'Weight' values

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#46]

**Comment by mghipparagi** [comment]
## Steps To Reproduce
1. Enter the “Age” value.
2. Enter a valid value in “Height” field.
3. Enter a valid value in “Weight” field.

## Actual Result

BMI value is displayed when the user click on the BMI box or anywhere in the page

## Expected Result

BMI value can be displayed when the user enters the 'Height' 'Weight' value With the 'Onchange' event of the two input boxes

## Comments

User will feel more comfortable than making him to click to view the value

**Comment by shanthasprim** [comment]
Working as Expected
