### ISSUE TITLE
Question No 1 / 1.6 - The BMI value remembers the old values and allows the user to select it

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#48]
## Steps To Reproduce

Double Click on the BMI field box
## Actual Result

A drop down appears showing the old value which is selectable.
## Expected Result

A drop down should not appear showing the old value which is selectable.
## Comments

This is a Readonly Field which is autogenerated and never allow the user to select anything in this.

**Comment by shanthasprim** [comment]
Fixed. Working as Expected.
