### ISSUE TITLE
Question No 1/ 1.8 - Hand symbol is shown on 'Mouse Over' on the text “How Old are you?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#50]
## Steps To Reproduce

Do a  'Mouse Over' on the text “How Old are you?”
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Issue Fixed
