### ISSUE TITLE
Question No 1/ 1.9 - BMI Calculation is shown wrongly sometimes

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#51]
## Steps To Reproduce
1. Enter a invalid value for 'Height' and 'Weight'
2. BMI value is shown
3. Come back again to Ques 1 and change a valid value for  'Height' and 'Weight'
## Actual Result

New BMI value loads but loads a wrong value
## Expected Result

Correct BMI value should be shown

**Comment by shanthasprim** [comment]
Working as Expected
