### ISSUE TITLE
Question No 1/ 1.10 - The Calculated BMI value can be shown with different colour codes validation against the normal Range

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#52]
## Steps To Reproduce
1. Enter the “Age” value.
2. Enter a valid value in “Height” field.
3. Enter a valid value in “Weight” field.
## Actual Result

The Calculated BMI is displayed
## Expected Result

The Display can be displayed with different colour codes
1. Yellow - below the normal range
2. Green - in the normal range
3. Red – Above the normal range

The Normal Ranges differs with Height and Weight so correct formula needs to be implemented to give a correct range.
We can check some BMI charts available online to get these formulas

**Comment by shanthasprim** [comment]
Not needed right now
