### ISSUE TITLE
Question No 2 / 2.1 - The Waist value is displayed only in inches in the option

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#53]
## Steps To Reproduce

Goto Question No 2
## Actual Result

The Waist value is displayed in inches
## Expected Result

The Waist value should be displayed in inches along with the cm value

The cm value can be displayed as 
Below 33” - (0-83.82 cms)

**Comment by shanthasprim** [comment]
Display fixed now
