### ISSUE TITLE
Question No 2 / 2.2 - Hand symbol is shown on 'Mouse Over' on the text “Fantastic! We are almost done with the numbers. Your waist size acts as an important predictor of your health. What is your Waist Circumferance? Please indicate your waist size or your jeans size.”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#54]
## Steps To Reproduce

Do a  'Mouse Over' on the text ““Fantastic! We are almost done with the numbers. Your waist size acts as an important predictor of your health. What is your Waist Circumferance? Please indicate your waist size or your jeans size.”
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Fixed
