### ISSUE TITLE
Question No 3 / 3.1 - Hand symbol is shown on 'Mouse Over' on the text “Do you consider yourself active?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#55]

**Comment by mghipparagi** [comment]
## Steps To Reproduce

Do a  'Mouse Over' on the text “Do you consider yourself active?”

## Actual Result

Hand symbol is displayed

## Expected Result

Hand symbol should not be displayed

## comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Fixed
