### ISSUE TITLE
Question No 3 and Question No 4 / 4.1 Question No 4 should not be displayed on selecting “No” in Question No 3 of the Physical activity

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#56]
## Steps To Reproduce
1. Goto Question No 3
2. Under “Do you consider yourself active?” Select “No”.
## Actual Result

Question No 4 asking for “How long does each session last” is displayed
## Expected Result

Question No 4 should not be displayed

**Comment by shanthasprim** [comment]
Working as Expected
