### ISSUE TITLE
Question No 4 / 5.1 - Hand symbol is shown on 'Mouse Over' on the text “Being physically active has its own potential benefits. How often do you think you find the time to exercise or play your favourite sport in a week?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#57]
## Steps To Reproduce

Do a  'Mouse Over' on the text ““Being physically active has its own potential benefits. How often do you think you find the time to exercise or play your favourite sport in a week?”
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed'
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed
