### ISSUE TITLE
Question No 4 / 5.2 - Hand symbol is shown on 'Mouse Over' on the text “How long does each session last?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#58]
## Steps To Reproduce

Do a  'Mouse Over' on the text ““How long does each session last?”
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Fixed. Hence Closing
