### ISSUE TITLE
Question No 4 / 5.3 - Question No 4 allows “Select Duration” value to be added in the “How long does each session last?” drop down

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#59]
## Steps To Reproduce

Select the “Select Duration” value in the “How long does each session last?” drop down
## Actual Result

User is allowed to select “Select Duration” value and proceed to next question
## Expected Result

User should not be allowed to select “Select Duration” value and proceed to next question
## Comments

Make the “Select Duration” option readonly.

**Comment by shanthasprim** [comment]
Fixed. Option made readonly
