### ISSUE TITLE
Entering wrong entries in the Next Sign Up page does not  show proper error message after clicking the 'Next' button

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#6]
## Steps to reproduce
1.  Sign up DGC for HCP User
2. Enter 'Email, 'Password' and 'Verification Code' correctly.
   3.A Page with many field open (About Practice)
3. Enter wrong entry or leave the mandatory fields as empty
4. Click on 'Next' button.
## Actual Result

Error message is displayed
## Expected Result

Should display appropriate error message

**Comment by shanthasprim** [comment]
Working as Expected hence closing the issue.
