### ISSUE TITLE
Question No 4 / 5.6 - Question No 4 should not allow the user to Question 5 without entering value for both “Times” selection image and “Select Duration” value

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#62]
## Steps To Reproduce
1. Goto Question No 3
2. Select “Yes” button
3. Page is taken to Question 4
4. Dont select anything and click on 'Next' button
## Actual Result

User is allowed to go the next Question
## Expected Result

User Should not allowed to go to next question
## Comments

Selecting “Yes” in Question No 3 states that the user is physically active. So Ques No 4 whcih has the activity details cannot be left empty

**Comment by shanthasprim** [comment]
Fixed
