### ISSUE TITLE
Question No 4 / 5.7 - Clicking on the “Times” image sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#63]
## Steps To Reproduce
1. Goto Question No 3
2. Select “Yes” button
3. Page is taken to Question 4
4. Click on any “Times” image
## Actual Result

Clicking on the “Times” image sometimes shows the image icon border 
## Expected Result

Clicking on the “Times” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Display Fixed now
