### ISSUE TITLE
Question No 4 / 5.8 - Clicking on the “Times” image showing the image icon border is not saved 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#64]
## Steps To Reproduce
1. Goto Question No 3
2. Select “Yes” button
3. Page is taken to Question 4
4. Click on any “Times” image (image border is shown)
5. Click on “Next” button.
6. Click on “Back” button in Question No 5 page.
## Actual Result

The selected “Times” image value is not shown on the Ques No 4 page
## Expected Result

The selected “Times” image value should be stored and shown on the Ques No 4 page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Fixed. Could not reproduce now.
