### ISSUE TITLE
Question No 5 / 6.1 - Hand symbol is shown on 'Mouse Over' on the text “Your perception of your health will determine what choices you make on a daily basis. So, tell us when you look at yourself, how healthy do you think you are right now?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#65]

**Comment by mghipparagi** [comment]
## Steps To Reproduce

Do a  'Mouse Over' on the text “Your perception of your health will determine what choices you make on a daily basis. So, tell us when you look at yourself, how healthy do you think you are right now?”

## Actual Result

Hand symbol is displayed

## Expected Result

Hand symbol should not be displayed

## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Fixed
