### ISSUE TITLE
Question No 5 / 6.2 - Clicking on the “Health and Well-being” image sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#66]
## Steps To Reproduce
1. Goto Question No 5
2. Click on any “Health and Well-being” image
## Actual Result

Clicking on the “Health and Well-being” image sometimes shows the image icon border 
## Expected Result

Clicking on the “Health and Well-being” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Working as Expected
