### ISSUE TITLE
Question No 5 / 6.3 - Clicking on the “Health and Well-being” image showing the image icon border is not saved 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#67]
## Steps To Reproduce
1. Goto Question No 5
2. Click on any “Health and Well-being” image (image border is shown)
3. Click on “Next” button.
4. Click on “Back” button in Question No 6 page.
## Actual Result

The selected “Health and Well-being” image value is not shown on the Ques No 5 page
## Expected Result

The selected “Health and Well-being” image value should be stored and shown on the Ques No 5 page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Display Fixed and issue not reproducible.
