### ISSUE TITLE
Question No 6 / 7.1 - Hand symbol is shown on 'Mouse Over' on the text “It would be nice if you could brief us on any medical conditions you have previously dealt with. (You can click more than one options)”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#70]
## Steps To Reproduce

Do a  'Mouse Over' on the text “It would be nice if you could brief us on any medical conditions you have previously dealt with. (You can click more than one options)”
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Fixed
