### ISSUE TITLE
Question No 6 / 7.2 - Question No 6 does not allow the user to go to Ques No 7 without selecting any “Medical Condition” value but does not display any error message

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#71]
## Steps To Reproduce
1. Goto Ques No 6.
2. Dont select any check box and click on “Next” button
## Actual Result

Question No 6 does not allow the user to go to Ques No 7 without selecting any “Medical Condition” value
## Expected Result

Question No 6 should not allow the user to go to Ques No 7 without selecting any “Medical Condition” value and show a error message saying “Please select any option to proceed”

**Comment by shanthasprim** [comment]
"Please select any option" error message is displayed
