### ISSUE TITLE
Question No 6 / 7.3 - “I don't have any history of medical conditions” is misspelled as “ I donít have any history of medical conditions”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#72]
## Steps To Reproduce
1. Goto Ques No 6.
## Actual Result

“I don't have any history of medical conditions” is misspelled as “ I donít have any history of medical conditions”
## Expected Result

 “ I donít have any history of medical conditions” should be changed to “I don't have any history of medical conditions”

**Comment by shanthasprim** [comment]
Corrected.
