### ISSUE TITLE
Question No 6 / 7.4 - The other check box options should be greyed out (Made Readonly) when the user selects “I don't have any history of medical conditions” option

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#73]
## Steps To Reproduce
1. Goto Ques No 6.
2. check the “I don't have any history of medical conditions” option.
## Actual Result

The other check box options are visible
## Expected Result

The other check box options should be greyed out.
On the Second click of the same “I don't have any history of medical conditions” Option, It should be unchecked and the other options should be visible.
## comments

When a user selects  “I don't have any history of medical conditions” means the user does not have any medical problems and so the other options need not be editable for him/her.

**Comment by shanthasprim** [comment]
Not needed rite now
