### ISSUE TITLE
Question No 7 / 8.2 - Hand symbol is shown on 'Mouse Over' on the text “Now that we know about you, let's talk about medical history of people close to you. Are any of the following statements true?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#75]
## Steps To Reproduce

Do a  'Mouse Over' on the text “Now that we know about you, let's talk about medical history of people close to you. Are any of the following statements true?”
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed.
