### ISSUE TITLE
Question No 7 / 8.3 - Question No 7 does not allow the user to go to Ques No 8 without selecting any “Medical History” value but does not display any error message

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#76]
## Steps To Reproduce
1. Goto Ques No 7.
2. Dont select any check box and click on “Next” button
## Actual Result

Question No 7 does not allow the user to go to Ques No 8 without selecting any “Medical History” value
## Expected Result

Question No 7 should not allow the user to go to Ques No 8 without selecting any “Medical History” value and show a error message saying “Please select any option to proceed”

**Comment by shanthasprim** [comment]
"Please select any option" error message is displayed
