### ISSUE TITLE
Question No 7 / 8.4 - “I don't have a family history of medical conditions” is misspelled as “ I donít have a family history of medical conditions”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#77]
## Steps To Reproduce
1. Goto Ques No 7.
## Actual Result

“I don't have a family history of medical conditions” is misspelled as “ I donít have any history of medical conditions”
## Expected Result

 “ I donít have a family history of medical conditions” should be changed to “I don't have any history of medical conditions”

**Comment by shanthasprim** [comment]
Spelling corrected
