### ISSUE TITLE
Question No 7 / 8.5 - The other check box options should be greyed out (Made Readonly) when the user selects “I don't have a family history of medical conditions” option

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#78]
## Steps To Reproduce
1. Goto Ques No 7.
2. check the “I don't have a family history of medical conditions” option.
## Actual Result

The other check box options are visible
## Expected Result

The other check box options should be greyed out.
## Comments

When a user selects  “I don't have a family history of medical conditions” means he does not have any medical problems and so the other options need not be editable for him.

**Comment by shanthasprim** [comment]
not needed right now
