### ISSUE TITLE
Question No 8 / 9.2 - “My blood pressure levels are †higher than normal range and i am on medication.” should be rephrased as “My blood pressure levels are higher than normal range and i am on medication.”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#80]
## Steps To Reproduce
1. Goto Ques No 8.
## Actual Result

The Cardiovascular health options is displayed as “My blood pressure levels are †higher than normal range and i am on medication.”
## Expected Result

The Cardiovascular health options should be displayed as “My blood pressure levels are higher than normal range and i am on medication.”

**Comment by shanthasprim** [comment]
Spelling corrected
