### ISSUE TITLE
Question No 8 / 9.3 - Hand symbol is shown on 'Mouse Over' on the text “Let's assess your cardiovascular health! How would you describe your blood pressure levels?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#81]
## Steps To Reproduce

Do a  'Mouse Over' on the text “Let's assess your cardiovascular health! How would you describe your blood pressure levels?”
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Displayed Fixed
