### ISSUE TITLE
Question No 9 / 10.1 - Rephrase the sentence as  “When last tested, what were your blood pressure levels?  It's ok if you don't know your blood pressure levels.  You can skip this Question by clicking next.” displayed below the image icons 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#82]
## Steps To Reproduce
1. Goto Ques No 9.
## Actual Result

The sentence is displayed as  “When last tested what were your blood pressure levels? It's ok if you don't know your levels. Just click next.”displayed below the image icons. 
## Expected Result

The sentence should be displayed as
 “When last tested, what were your blood pressure levels?
 It's ok if you don't know your blood pressure levels. 
You can skip this Question by clicking next.” displayed below the image icons

**Comment by shanthasprim** [comment]
Display Fixed
