### ISSUE TITLE
Question No 9 / 10.2 - Clicking on the “Blood Pressure” images sometimes shows the image icon border 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#83]
## Steps To Reproduce
1. Goto Question No 9
2. Click on any “Blood Pressure” image
## Actual Result

Clicking on the “Blood Pressure image sometimes shows the image icon border 
## Expected Result

Clicking on the “Blood Pressure” image should not  show the image icon border

**Comment by shanthasprim** [comment]
Display fixed
