### ISSUE TITLE
Question No 9 / 10.3 - Clicking on the “Blood Pressure” image showing the image icon border is not saved 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#84]
## Steps To Reproduce
1. Goto Question No 9
2. Click on any “Blood Pressure” image (image border is shown)
3. Click on “Next” button.
4. Click on “Back” button in Question No 6 page.
## Actual Result

The selected “Blood Pressure” image value is not shown on the Ques No 9 page
## Expected Result

The selected “Blood Pressure” image value should be stored and shown on the Ques No 9 page
## Comments

The Issue is reproducible only when the image's border is clicked. Means the image value is actually not selected but the image icon is only selected and passed as a null value to the database.

**Comment by shanthasprim** [comment]
Display Fixed. Hence issue not reproducible.
