### ISSUE TITLE
Question No 9 / 10.4 - Hand symbol is shown on 'Mouse Over' on the text “When was the last time you checked your blood pressure?” and “When last tested what were your blood pressure levels? It's ok if you don't know your levels. Just click next.”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#85]
## Steps To Reproduce

Do a  'Mouse Over' on the text “When was the last time you checked your blood pressure?” and “When last tested what were your blood pressure levels? It's ok if you don't know your levels. Just click next.” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed.
