### ISSUE TITLE
Question No 9 / 10.5 - Restrict the Systolic input box value length to 3 digits

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#86]
## Steps To Reproduce
1. Enter the Systolic value as '456531231321' / '1243.14545'
2. Click the 'Next' button
## Actual Result

Systolic value is accepted
## Expected Result

Systolic value length has to be restricted
## Comments

invalid systolic value

**Comment by shanthasprim** [comment]
Validation done
