### ISSUE TITLE
Question No 9 /  - Restrict the Systolic value only with number and not any alphabets / special characters.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#87]
## Steps To Reproduce

1.Enter the Systolic value as 'gfdfj@$@#%'
2. Click the 'Next' button
## Actual Result

Systolic value is accepted
## Expected Result

Systolic value should not be accepted
## Comments

invalid systolic value

**Comment by shanthasprim** [comment]
Validation done
