### ISSUE TITLE
Question No 9 / 10.6 - Restrict the Diastolic input box value length to 3 digits

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#88]
## Steps To Reproduce
1. Enter the Diastolic value as 454543543523/ '56341.45454'
2. Click the 'Next' button
## Actual Result

Diastolic value is accepted
## Expected Result

Diastolic value length has to be restricted
## Comments

invalid Diastolic value

**Comment by shanthasprim** [comment]
Validation done
