### ISSUE TITLE
Question No 9 /  - Restrict the Diastolic value only with number and not any alphabets / special characters.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#89]
## Steps To Reproduce

1.Enter the Diastolic value as 'ggsdgsdj@$()@#%'
2. Click the 'Next' button
## Actual Result

Diastolic value is accepted
## Expected Result

Diastolic value should not be accepted
## Comments

invalid Diastolic value

**Comment by shanthasprim** [comment]
Validation done
