### ISSUE TITLE
Adding a Patient as a New User bu the HCP does not show the 'Employer' drop down values

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#9]
## Steps to reproduce
1. Login into DGC with HCP Login
2. Click HCP dropdown on the top left of the header
3. Click 'My Patients' -> '+Add Patient' -> 'New User'
4. Fill Step 1 and goto Step 2
5. Click on 'Employer' drop down in Step 2.
## Actual Result

Drop down does not have any value
## Expected Result

drop down should show the employer name or Employer name field needs to be removed

**Comment by shanthasprim** [comment]
Fixed and working as expected.
