### ISSUE TITLE
Question No 9 / 10.7 - User should enter the Diastolic value if the Systolic value is entered

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#90]
## Steps To Reproduce
1. Enter a value for Systolic field
2. Leave the Diastolic field empty
3. Click the 'Next' button
## Actual Result

User is allowed to go the next Question
## Expected Result

User Should not allowed to go to next question
## Comments

If the user does not enter both the values he should be accepted to goto next question. But if a single value either 'Systolic' or 'Diastolic' is entered and the other field is left empty then a error message should be displayed.

**Comment by shanthasprim** [comment]
Validation done
