### ISSUE TITLE
Question No 9 / 10.8 -  '0' should not be accepted in Systolic and Diastolic field

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#91]
## Steps To Reproduce
1. Enter 0 for Systolic field
2. Enter 0 for Diastolic field 
3. Click the 'Next' button
## Actual Result

User is allowed to go the next Question
## Expected Result

User Should not allowed to go to next question
## Comments

Leaving the field empty and entering 0 doesnot mean the same. Give a Alert that “Cannot enter a wrong value.If u are unaware of ur Blood Pressure value, leave the fields empty”

**Comment by shanthasprim** [comment]
Not a mandatory value
