### ISSUE TITLE
Question No 10 / 11.1 - Hand symbol is shown on 'Mouse Over' on the text “Cholesterol levels tell us a lot about your health. How would you describe your cholesterol levels?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#92]
## Steps To Reproduce

Do a  'Mouse Over' on the text “Cholesterol levels tell us a lot about your health. How would you describe your cholesterol levels?” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display Fixed
