### ISSUE TITLE
Question No 10 & Question No 11 / 12.1 - Question No 11 should not be displayed on selecting “ I am unaware about my cholesterol levels.” in Question No 10 of the Cholesterol levels page.

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#93]
## Steps To Reproduce
1. Goto Question No 10.
2. Under “Cholesterol levels tell us a lot about your health. How would you describe your cholesterol levels?” Select “I am unaware about my cholesterol levels.”
## Actual Result

Question No 11 asking for Questions like “When last tested, what were your cholesterol levels?” is displayed
## Expected Result

Question No 11 should not be displayed
## Comments

User cannot be expected to reply details about the cholestrol levels when they select the option of “I am unaware about my cholesterol levels.”

**Comment by shanthasprim** [comment]
Working as Expected
