### ISSUE TITLE
Question No 11 / 13.4 - Question No 11 allows “Select Option” value to be added in the “When last tested, what were your Triglyceride (TG) levels?” drop down

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#97]
## Steps To Reproduce

Select the “Select Option” value in the “When last tested, what were your Triglyceride (TG) levels?” drop down
## Actual Result

User is allowed to select “Select Option” value and proceed to next question
## Expected Result

User should not be allowed to select “Select Option” value and proceed to next question
## Comments

Make the “Select Option” option readonly.

**Comment by shanthasprim** [comment]
"Select Option" made readonly.
