### ISSUE TITLE
Question No 11 / 13.5 - Hand symbol is shown on 'Mouse Over' on the text “When last tested, what were your cholesterol levels?” , “ When last tested, what were your LDL "bad" cholesterol levels?” , “When last tested, what were your HDL "good" cholesterol levels?” and “ When last tested, what were your Triglyceride (TG) levels?” 

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#98]
## Steps To Reproduce

Do a  'Mouse Over' on the texts “When last tested, what were your cholesterol levels?” , “
When last tested, what were your LDL "bad" cholesterol levels?” ,”When last tested, what were your HDL "good" cholesterol levels?” and  “
When last tested, what were your Triglyceride (TG) levels?” phrases
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display fixed
