### ISSUE TITLE
Question No 12 / 14.1 - Hand symbol is shown on 'Mouse Over' on the text “Diabetes is one of the most debilitating chronic disease. Let's asses your risk for diabetes. Have you checked your blood sugar levels in the past one year?”

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Web#99]
## Steps To Reproduce

Do a  'Mouse Over' on the text “Diabetes is one of the most debilitating chronic disease. Let's asses your risk for diabetes. Have you checked your blood sugar levels in the past one year?” phrase

Do a  'Mouse Over' on the text “Diabetes is one of the most debilitating chronic disease. Let's asses your risk for diabetes. Have you checked your blood sugar levels in the past one year?” phrase
## Actual Result

Hand symbol is displayed
## Expected Result

Hand symbol should not be displayed
## Comments

Hand symbol should be shown only when the user is allowed to 'Click'/'Select' some option or button

**Comment by shanthasprim** [comment]
Display fixed
